### ISSUE TITLE
ทำ p1&2 movement, aniamtion

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#1]
-การเดิน
-อนิเมชั่นการเดิน

**Comment by pubestpubest** [comment]
Demo : https://scratch.mit.edu/projects/722507922/editor
![image](https://user-images.githubusercontent.com/110964000/189407582-24a1aa6d-eabb-4ae5-ba38-6f002c2ba987.png)

**Comment by pubestpubest** [comment]
check ด้านที่หันไปเพื่อแสดงอนิเมชั่น 
![image](https://user-images.githubusercontent.com/110964000/189408391-bf13f540-e43e-4257-bb66-cf7227ce4961.png)
check ทิศ > check ว่าถืออะไรหรือไม่ > ส่งไป module animation แยก
![image](https://user-images.githubusercontent.com/110964000/189408725-b54fe0b4-a59d-4995-ba19-0c9d2bf73872.png)
![image](https://user-images.githubusercontent.com/110964000/189408772-aa3fc63e-aae2-48af-8d08-a52506231c94.png)
![image](https://user-images.githubusercontent.com/110964000/189408810-805fd770-a6dc-4815-b2f1-0bb2af8632ef.png)

**Comment by pubestpubest** [comment]
module reset animation 
![image](https://user-images.githubusercontent.com/110964000/189409247-8dcee065-cb73-4393-aad5-9141e2d85074.png)

**Comment by pubestpubest** [comment]
รวม event 
![image](https://user-images.githubusercontent.com/110964000/189409419-2e820337-af29-4bec-922c-d11c47c8a36d.png)
![image](https://user-images.githubusercontent.com/110964000/189409466-1b452225-7cbd-4175-a09a-e005ee171bcc.png)
โยนเนื้อ
![image](https://user-images.githubusercontent.com/110964000/189409565-fc91a5fa-191a-44b2-8df1-ac0a5f81e5fc.png)

**Comment by pubestpubest** [comment]
10/09/22
Feature
- มี animation
> -เดิน 4 ทิศ
> -ชนขอบร้าน
> -เก็บเนื้อจากกล่อง, จากเนื้อบนพื้น
> -โยนเนื้อ

**Comment by NongPhai** [comment]
12/09/22
-บัคเกิดตรงการโยนเนื้อ
เมื่อกดโยนเนื้อจะทำให้เนื้อตกลงไปที่ด้านหน้าของผู้โยน ทำให้เวลาโยนเนื้อแล้วหันหน้าไปทางอื่นด้วยความเร็วจะทำให้เนื้อที่ถูกโยนออกไปเปลี่ยนไปตกทิศที่ผู้โยนหันหน้าอยู่ เช่นโยนเนื้อไปทางด้านซ้ายแต่หันหน้าไปทางขวาทันที ทำให้เนื้อจะพุ่งไปอยู่ด้านขวา

**Comment by pubestpubest** [comment]
### **Update 130922**

- Bug โยนเนิ้อแก้แล้ว
- Clean code แก้โค้ดเก่า(Hard Code)เรียบร้อย
- เพิ่ม Bun
- ทอด Bun
- Sound effect เล็กน้อย

Demo : https://scratch.mit.edu/projects/731374901
![image](https://user-images.githubusercontent.com/110964000/189913480-4077f847-5c98-439c-8b0f-0a16385e8eab.png)
