### ISSUE TITLE
ทดลองเล่นเกม

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#13]

**Comment by NongPhai** [comment]
จากการทดลองเล่นในmode normal รู้สึกว่าเวลาในเกม180วินาทีมันนานไปและเวลาต่อ1เมนูค่อนข้างน้อย หลังจากลองปรับเวลาดูแล้วก้ทำให้รู้สึกว่าเวลาในการเล่นเกมมีความเหมาะสมมากขึ้น
