### ISSUE TITLE
บัค ขั้นตอนการรวมเนื้อกับขนมปัง

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#16]

**Comment by NongPhai** [comment]
เมื่อนำขนมปังเปล่าลงไปในกระทะแล้วหยิบออกมา ผลลัพธ์ที่ได้คือได้ขนมปังที่มีเนื้ออยู่ข้างในติดมาด้วย ซึ่งไม่ได้ใส่เนื้อเข้าไปในตอนแรก

**Comment by NongPhai** [comment]
เกิดบัคที่เมื่อโยนobjectออกนอกแมพมันจะทะลุออกไปข้างนอกซึ่งobjectไท่ควรออกนอกแมพ

**Comment by NongPhai** [comment]
ขั้นตอนการรวมเนื้อกับขนมปัง
-เมื่อนำขนมปังวางบนจานแล้วค่อยวางเนื้อตามผลลัพธ์จะออกมาเป็นเบอร์เกอร์
-ถ้านำเนื้อวางแล้วค่อยนำขนมปังวางตามผลลัพธ์จะทำให้objectหายไปและไม่สามารถหันหน้าตัวละครได้

**Comment by pubestpubest** [comment]
แก้เรียบร้อยละ
