### ISSUE TITLE
ทำ Mapping

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#2]
-วาง sprite สิ่งของ(กล่องวัตถุดิบ, กระทะ, เขียง, etc.)
-ขอบด่าน
-mask ของด่าน

**Comment by GodMonera** [comment]
![mapping](https://user-images.githubusercontent.com/110964762/189964754-9495908d-89b4-40e3-9309-edbcad22173e.jpg)
