### ISSUE TITLE
ทำ Intereaction กับวัตถุดิบ

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#3]
-หยิบวัตถุดิบจากกล่อง
-หยิบวัตถุดิบจากพื้น
-โยนวัตถุดิบ

**Comment by GodMonera** [comment]
โยนตามทิศทางที่หันหน้า
![image](https://user-images.githubusercontent.com/110964762/189982365-b0633377-c071-4503-b990-d5666513c60d.png)
