### ISSUE TITLE
ทำ Intereaction กับ map (โต๊ะ, etc.)

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#4]
- [ ] โต๊ะวางของ
- โต๊ะส่งอาหาร
- - [ ] โต๊ะ grab
- - [ ] โต๊ะ line man
- - [ ] โต๊ะ food panda

**Comment by pubestpubest** [comment]
ตำแหน่ง
![image](https://user-images.githubusercontent.com/110964000/189991215-c4e5a705-bb38-450a-bf77-275b85de9611.png)

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/191415592-2a9efa51-89fe-44d5-9342-9d54cb215644.png)
