### ISSUE TITLE
ทำอาหาร!!

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#5]
- [x] เอาวัตถุดิบไปเตรียม _(สับ ทอด นวด บลาๆๆๆ)_
- [x] ทอด
- [ ] สับ
- [x] เอาวัตถุดิบมารวมกัน _(ex.ขนมปัง + เนื้อ = เบอร์เกอร์, เบอร์เกอร์+จาน)_
![image](https://user-images.githubusercontent.com/110964000/189985476-1a424617-963d-4d45-81b5-2e32868f18d5.png)
![image](https://user-images.githubusercontent.com/110964000/189985573-0cf60fa8-fd73-4b71-92b5-50284c22e239.png)

**Comment by pubestpubest** [comment]
![image](https://user-images.githubusercontent.com/110964000/189541214-60248998-2c71-4b5c-aab9-3940b5ba2e69.png)
update
-เอาเนื้อไปทอด
![image](https://user-images.githubusercontent.com/110964000/189541247-b5de0806-6560-41d5-bc4c-bba3d894439a.png)
![image](https://user-images.githubusercontent.com/110964000/189541254-026c4dde-f93f-40ec-82de-7b071d7ecc34.png)
bug animation รอแก้

**Comment by pubestpubest** [comment]
-bug animation แก้แล้ว

**Comment by pubestpubest** [comment]
เพิ่ม ขนมปัง, ทอดขนมปัง
![image](https://user-images.githubusercontent.com/110964000/189915247-bb299eea-c764-4cb0-9c16-02fda1e18bfd.png)

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/191415667-d860bf61-224e-4f17-8cee-88ced5bc9b08.png)
