### ISSUE TITLE
ทำระบบ score

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#6]
### คะแนนที่ได้รับของแต่ละเมนู
- French fries 10
- Salad 10
- Small Hamburger 20
- Large Hamburger 30
### Score
- 85% ขึ้นไปได้ 3 ดาว
- 75% ขึ้นไปได้ 2 ดาว
- 50% ขึ้นไปได้ 1.5 ดาว
- 30% ขึ้นไปได้ 1 ดาว

**ตำแหน่ง**
![image](https://user-images.githubusercontent.com/110964000/189992194-ff24b298-b555-4b88-9089-d6e77be85948.png)

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/191415520-59b8395d-10de-4dd7-a368-aba7e1142da4.png)
