### ISSUE TITLE
ทำภาพประกอบที่ใช้ในเกม

### ISSUE THREAD

**Issue by pubestpubest** [pubestpubest/CPE65BasicComProjGroup3#8]
-วัตถุดิบ
-ตัวละคร
-แมพเกม

**Comment by suwichada012** [comment]
![IMG_3585](https://user-images.githubusercontent.com/95045750/189181981-60e66dad-4227-45de-9ca4-6f89be84418d.jpg)

**Comment by suwichada012** [comment]
![S__10362883](https://user-images.githubusercontent.com/95045750/189193626-08213d1c-08e0-4f51-9e87-26af59b39c63.jpg)
![245F149E-1389-4E25-AD65-FD45D30E2625](https://user-images.githubusercontent.com/95045750/189193646-666259bc-f938-422d-bf15-7927a9119784.jpg)
![E215A982-8155-4EBC-8F4D-BA9954EF61A1](https://user-images.githubusercontent.com/95045750/189193663-2ffee79c-d011-43e2-b0e0-b7ed7c0f553b.jpg)
![5026E00C-62EA-4456-978E-3D748AC6A1C5](https://user-images.githubusercontent.com/95045750/189193679-3ee8e431-fa75-424f-946f-258574cfc9cd.jpg)
![B73C5A99-6DC0-4A06-AD8B-3A37CDA82F69](https://user-images.githubusercontent.com/95045750/189193697-78e8d6c1-9114-40d4-8bfe-e748f4e60cad.jpg)
![EE231C7A-AA8F-405D-944A-A3D4AA93A6E5](https://user-images.githubusercontent.com/95045750/189193708-a632a89e-7621-4501-a50d-55720a1ad2bb.jpg)
![2B44EC30-D8F8-4C62-80CA-81CD06AF2E88](https://user-images.githubusercontent.com/95045750/189193718-d7a762a6-a0df-4e25-bce7-1b75edf4d2fc.jpg)

ร่างงาน

**Comment by suwichada012** [comment]
อ
![image](https://user-images.githubusercontent.com/95045750/189498670-be20bc13-f98d-4f21-9b22-4b454215dc6c.jpeg)
![image](https://user-images.githubusercontent.com/95045750/189498675-a16fbb2e-edc5-43b9-b9e4-348747f4103c.jpeg)
![image](https://user-images.githubusercontent.com/95045750/189498681-8b843495-bbbe-4deb-8426-03e7615f263e.jpeg)
![image](https://user-images.githubusercontent.com/95045750/189498686-b1203fb9-01b3-4314-a5f4-b68a0116bb36.jpeg)
![image](https://user-images.githubusercontent.com/95045750/189498692-55e05cb2-0c08-4fd6-8f63-68efcd3dcd86.jpeg)ัพเดต

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/189539564-e42e8935-7e06-4247-ad2c-9966cc10ba12.png)
![image](https://user-images.githubusercontent.com/95045750/189539579-4e7c0b1f-513c-48ad-bb0b-498187a559c8.png)
![image](https://user-images.githubusercontent.com/95045750/189539583-ab46a5d9-3ca4-4509-8218-c20fa33cc934.png)
![image](https://user-images.githubusercontent.com/95045750/189539612-f01bebc7-e850-403a-8c69-ce2a5b04cd0b.png)
![image](https://user-images.githubusercontent.com/95045750/189539591-b0d6d376-8d6d-430a-9818-b048ebab3f38.png)![image](https://user-images.githubusercontent.com/95045750/189539597-3b3b2e9f-acd7-4b1c-b4be-95e6f123c533.png)

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/189714709-140e1bbe-c6fa-44b3-8a53-7d0b35eced1f.png)

**Comment by GodMonera** [comment]
ต้องมีรูปกระทะเฉยๆกับกระทะที่กำลังทอดด้วยมั้ยครับ กริล กับเขียงก็เหมือนกัน

**Comment by suwichada012** [comment]
> ต้องมีรูปกระทะเฉยๆกับกระทะที่กำลังทอดด้วยมั้ยครับ กริล กับเขียงก็เหมือนกัน

มีๆแต่ยังไม่ได้วาด

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/189974100-a647d4a4-50e4-4378-8454-bf47f7ce374e.jpeg)

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/189987329-d637d4fb-9536-4ffd-941a-d95dcb6b82fc.png)
![image](https://user-images.githubusercontent.com/95045750/189987353-3401bdf0-f128-4855-9983-62d71c55853c.png)
![image](https://user-images.githubusercontent.com/95045750/189987410-85d9a68c-630b-4b65-adf7-bba5274d58a3.png)
![image](https://user-images.githubusercontent.com/95045750/189987437-198b1ed6-30a8-4cdd-9a1b-fc92db1459f6.png)

**Comment by suwichada012** [comment]
![image](https://user-images.githubusercontent.com/95045750/190077001-524807f1-4fc8-4751-86cb-30a8e6a75a81.jpeg)
![image](https://user-images.githubusercontent.com/95045750/190077014-0fec2ba9-925b-452b-bf1c-2dcd84390e24.jpeg)
![image](https://user-images.githubusercontent.com/95045750/190077311-01c8eecc-ffe2-4788-8bfd-5eba5bbe3afb.png)

**Comment by GodMonera** [comment]
รบกวนแก้ปุ่มนี้ให้ขอบเข้มกว่านี้ได้ไหมคับ เพราะว่าตอนเอาไปใส่ในเกมจะดูสวยขึ้น
![190678594-5916b099-d22c-47cc-a490-0487ff361df0](https://user-images.githubusercontent.com/110964762/190709954-7aa8d849-4f97-4d35-a6e1-1eece695e590.png)

**Comment by suwichada012** [comment]
ตอนนี้ เหลือ ตกแต่งแมพกับทำตัวละคร

**Comment by suwichada012** [comment]
> รบกวนแก้ปุ่มนี้ให้ขอบเข้มกว่านี้ได้ไหมคับ เพราะว่าตอนเอาไปใส่ในเกมจะดูสวยขึ้น
> 
> ![190678594-5916b099-d22c-47cc-a490-0487ff361df0](https://user-images.githubusercontent.com/110964762/190709954-7aa8d849-4f97-4d35-a6e1-1eece695e590.png)
> 
> 

อัพในdrive

**Comment by pubestpubest** [comment]
https://drive.google.com/drive/folders/10QQ9CTRJCq8gf0XYT-gfii6pRdIt2cG0
